name: RelicBuild-Adventure # the name of the plugin.

version: 1.0.1 # the version of the plugin.

main: com.pezapp.relicbuildadventure.Plugin # the main class of the plugin.

api-version: 1.13

softDepend: [RelicBuild-Core]

# NOTE: registering command that is already registered in core will break it