name: RelicBuild # the name of the plugin.

version: 1.1.3 # the version of the plugin.

main: com.pezapp.relicbuild.Plugin # the main class of the plugin.

api-version: 1.13

# Commands:
commands:
   relicbuild:
      description: Plugin info command.
      usage: /<command>
      permission: RelicBuild.basic
      permission-message: You don't have <permission>
   grantOp:
      description: Grants honorary Operator status to all relicbuild items within level
      usage: /<command> [player] <level>
      permission: RelicBuild.basic
      permission-message: You don't have <permission>
   remOp:
      description: Revokes honorary Operator status to all op perms
      usage: /<command> [player]
      permission: RelicBuild.basic
      permission-message: You don't have <permission>
   listOps:
      description: Lists all current temporary ops
      usage: /<command>
      permission: RelicBuild.basic
      permission-message: You don't have <permission>
   rbmysqlexe:
      description: Executes mysql select+ command
      usage: /<command>
      permission: RelicBuild.basic
      permission-message: You don't have <permission>
   rbmysqlupdate:
      description: Executes mysql update command
      usage: /<command>
      permission: RelicBuild.basic
      permission-message: You don't have <permission>
   enableTrails:
      description: Enables trails.
      usage: /<command>
      permission: RelicBuild.basic
      permission-message: You don't have <permission>
   disableTrails:
      description: Disables trails.
      usage: /<command>
      permission: RelicBuild.basic
      permission-message: You don't have <permission>